name: Lint
on:
  push:
    branches:
      - "master" 
  pull_request:
    branches:
      - "master" 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Luacheck
        uses: lunarmodules/luacheck@v1.1.1

      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
